[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.8.0"
aws-sdk-s3 = { version = "1.92.0" }
log = "0.4.27"
tokio = { version = "1.45.1", features = ["macros", "rt", "rt-multi-thread"] }
pretty_env_logger = "0.5.0"
# Should match with pretty_env_logger
env_logger = "0.10"
wasmer = "6.0.1"
